<?php

    $_news = $this->getNews();
    $_news_id = $_news->getId();
    $_customer_name = Mage::helper('inchoo_newwssii')->getCustomerName();
    $_comments_enabled = Mage::helper('inchoo_newwssii')->getCommentsEnabled();

?>

<h1>News</h1>

<div>

    <?php echo $_news->getNews(); ?>
    <br>
    <br>
    <br>

</div>

<h2>Comments</h2>

<?php if($_comments_enabled === '0') : ?>

    <p>Comments are disabled</p>

<?php elseif(!$this->getCollection()->count()) : ?>

    <p>No comments</p>

<?php else:  ?>

    <?php foreach ($this->getCollection() as $_comment ): ?>
        <p><?php echo $this->escapeHtml($_comment->getComment()); ?></p>
    <?php endforeach; ?>


<?php endif; ?>
<br>
<?php if($_comments_enabled === '1') : ?>
    <?php if ($this->helper('customer')->isLoggedIn()): ?>
    <form method="post" class="scaffold-form" action="<?php echo $this->getUrl('news/detail/commentpost/', array('id' => $_news_id)) ?>">
        <div class="fieldset">
            <ul class="form-list">
                <li class="wide">
                    <div class="wide">
                        <label for="comment" class="required"><em>*</em>Comment</label>
                        <div class="input-box">
                            <textarea name='comment' id='comment'></textarea>
                        </div>
                    </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="name">Comment as:</label>
                        <div class="input-box">
                            <input type='text' name='name' id='name' value="<?php echo $this->escapeHtml($_customer_name); ?>" readonly/>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
        <div class="buttons">
            <button type="submit" title="Submit" class="button"><span><span>Submit</span></span></button>
        </div>
    </form>
    <?php else: ?>
        <br>
        <p>You should login before commenting man!</p>

    <?php endif; ?>
<?php endif; ?>
