<?php
$latest_news = $this->getLatestNews(5);
?>

<?php if($latest_news->count()) : ?>

    <h2 class="widget-title">Latest news</h2>

    <ul class="latest-news">

    <?php foreach($latest_news as $news): ?>
        <a href="<?php echo $this->getUrl('news/detail/view', array('id' => $news->getId())) ?>"><li><?php echo $news->getNews(); ?></li></a>

    <?php endforeach ?>

    </ul>

    <a href="<?php echo $this->getUrl('news/index/showall') ?>">
    <h3 class="widget-title">View All News</h3>
    </a>

<?php endif ?>

